# Generated by Django 3.0.1 on 2020-09-24 10:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=150, null=True)),
                ('pin_code', models.CharField(blank=True, max_length=10, null=True)),
                ('contact_no', models.CharField(blank=True, max_length=14, null=True)),
                ('refer_code', models.CharField(blank=True, max_length=14, null=True)),
                ('default', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Adresses',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_no', models.CharField(blank=True, max_length=10, null=True)),
                ('book_title', models.CharField(blank=True, max_length=100, null=True)),
                ('book_type', models.CharField(default='Secondary', max_length=20)),
                ('book_image1', models.ImageField(blank=True, null=True, upload_to='media')),
                ('book_image2', models.ImageField(blank=True, null=True, upload_to='media')),
                ('book_image3', models.ImageField(blank=True, null=True, upload_to='media')),
                ('book_image4', models.ImageField(blank=True, null=True, upload_to='media')),
                ('book_mrp', models.IntegerField(default=1)),
                ('book_price', models.IntegerField(default=1)),
                ('book_discount_price', models.IntegerField(blank=True, default=1, null=True)),
                ('book_category', models.CharField(max_length=30)),
                ('book_stock', models.IntegerField(default=1)),
                ('ideal_course', models.CharField(max_length=70)),
                ('ideal_sem', models.CharField(max_length=20)),
                ('publication_name', models.CharField(max_length=50)),
                ('authors', models.CharField(max_length=100)),
                ('edition', models.CharField(max_length=40)),
                ('slug', models.SlugField(default='test-product')),
            ],
            options={
                'verbose_name_plural': 'Books',
                'ordering': ('book_stock',),
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(blank=True, max_length=15, null=True)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('ordered_date', models.DateTimeField()),
                ('ordered', models.BooleanField(default=False)),
                ('being_delieverd', models.BooleanField(default=False)),
                ('recieved', models.BooleanField(default=False)),
                ('refund_requested', models.BooleanField(default=False)),
                ('refund_granted', models.BooleanField(default=False)),
                ('delievery_address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='book.Address')),
            ],
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('accepted', models.BooleanField(default=False)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Order')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0.0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('payment_option', models.CharField(blank=True, max_length=20, null=True)),
                ('payment_sender_name', models.CharField(blank=True, max_length=50)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered', models.BooleanField(default=False)),
                ('product_quantity', models.IntegerField(default=1)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.Book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='book.Payment'),
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(to='book.OrderProduct'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='BookRequests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(blank=True, max_length=150, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=120, null=True)),
                ('book_title', models.CharField(blank=True, max_length=150, null=True)),
                ('book_mrp', models.IntegerField(default=1)),
                ('book_category', models.CharField(max_length=50)),
                ('ideal_course', models.CharField(max_length=70)),
                ('ideal_sem', models.CharField(max_length=40)),
                ('publication_name', models.CharField(max_length=50)),
                ('authors', models.CharField(max_length=100)),
                ('edition', models.CharField(max_length=60)),
                ('request_date', models.DateTimeField(blank=True, null=True)),
                ('book_status', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Book requests',
            },
        ),
    ]
