# Generated by Django 3.0.1 on 2020-09-24 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_discount_price',
            field=models.IntegerField(blank=True, max_length=20, null=True),
        ),
    ]
