# Generated by Django 3.0.1 on 2020-09-24 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20200924_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_discount_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
