# Generated by Django 3.0.1 on 2020-09-25 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_auto_20200925_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='ideal_course',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='book',
            name='ideal_sem',
            field=models.CharField(max_length=150),
        ),
    ]
