# Generated by Django 3.0.1 on 2020-09-28 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_auto_20200925_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_stock',
            field=models.IntegerField(default=0),
        ),
    ]
