# Generated by Django 3.0.1 on 2020-09-28 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_auto_20200928_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_stock',
            field=models.IntegerField(default=1),
        ),
    ]
