# Generated by Django 3.0.1 on 2020-10-04 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_auto_20200928_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_board',
            field=models.CharField(default='Maharshtra', max_length=20),
        ),
    ]
