# Generated by Django 3.0.1 on 2020-10-04 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_book_book_board'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_board',
            field=models.CharField(blank=True, default='Maharshtra', max_length=20, null=True),
        ),
    ]
