# Generated by Django 3.0.1 on 2020-10-04 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0011_auto_20201004_1813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_category',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
