# Generated by Django 3.0.1 on 2020-11-11 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0013_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='message_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
