# Generated by Django 3.2.4 on 2022-05-11 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0014_messages_message_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delievery_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
