# Generated by Django 3.2.4 on 2022-05-11 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0015_order_delievery_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_chages',
            field=models.FloatField(default=0.0),
        ),
    ]
